#Database details

mysql:
    host:
    port:
    database:
    username:
    password:
    
    table:
        game:
        gui:
        game_log:

#Lobby

spawn:
    x:
    y:
    z:
    yaw:
    pitch:
    
world:            