name: Minigames
version: 2.0.0
main: me.elgamer.minigames.Main
description: Core module of the minigames server, handles adding/removing games, main guis and the main lobby.
depend: [Multiverse-Core]
api-version: 1.16
commands:
    game:
        usage: /<command>
        description: Adds/Removes a game on the server.
    gui:
        usage: /<command>
        description: Adds/Removes an existing game in the gui to make it accessible to players.